---
- name: Install Apache
  hosts: allservers
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
    
    - name: Check Apache-service started
      service:
        name: apache2
        state: started

