---
# tasks file for WebServers
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install Services
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  loop: "{{ packages }}"

- name: Service is present?
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ services }}"
